[package]
name = "systems"
version = "0.1.0"
authors = ["Spyros Roum <spyrosr1@gmail.com>"]
edition = "2018"

[dependencies]
macroquad = { version = "0.3", no-default-features = true }
egui-macroquad = "0.6.1"
